# Generated by Django 4.1.7 on 2023-03-16 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patient_fullname', models.CharField(default=True, max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_fullname', models.CharField(default=True, max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('reg', models.PositiveIntegerField(default=0)),
                ('specialization', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='App1.category')),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
