# Generated by Django 4.1.7 on 2023-03-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_patientproblem_doctorsolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAndSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(default=True, max_length=400)),
                ('solution', models.CharField(default=False, max_length=400)),
                ('doctor', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='App1.doctordetail')),
                ('patient', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='App1.patientdetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='patientproblem',
            name='doc_choice',
        ),
        migrations.RemoveField(
            model_name='patientproblem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patientproblem',
            name='your_choice',
        ),
        migrations.DeleteModel(
            name='DoctorSolution',
        ),
        migrations.DeleteModel(
            name='PatientProblem',
        ),
    ]
